routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\MovieController;
use App\Http\Controllers\GenreController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Route::get('/email', [AuthController::class, 'email']);

Route::get('/', function () {
    return view('landing');
});

Route::get('/livestream', function () {
    return view('livestream');
});

Route::get('/livestream2', function() {
    return view('livestream2');
});

Route::get('/login', function () {
    return view('login');
})->middleware(['auth','verified'])->name('login');

Route::get('/home-movie', function() {
    return view('home-movie');
});

Route::get('/home-movie1', function() {
    return view('home-movie1');
});

Route::get('/home-movie2', function() {
    return view('home-movie2');
});

Route::get('/home-movie3', function() {
    return view('home-movie3');
});


Route::resource('movies', MovieController::class);

Route::get('/movies',[MovieController::class, 'index'])->name('index');
Route::get('/create',[MovieController::class, 'create'])->name('create');
Route::post('store/',[MovieController::class, 'store'])->name('store');
Route::get('show/{movie}',[MovieController::class, 'show'])->name('show');
Route::get('edit/{movie}',[MovieController::class, 'edit'])->name('edit');
Route::put('edit/{movie}',[MovieController::class, 'update'])->name('update');
Route::delete('/{movie}',[MovieController::class, 'destroy'])->name('destroy');



require __DIR__.'/auth.php';

resources/views/movies/create.blade.php
@extends('adminLayout')


    
@section('content')

<link rel="shortcut icon" type="image/x-icon" href="assets/img/favicon.png">
    <link rel="stylesheet" href="assets/css/bootstrap.min.css">
    <link rel="stylesheet" href="assets/plugins/fontawesome/css/fontawesome.min.css">
    <link rel="stylesheet" href="assets/plugins/fontawesome/css/all.min.css">
    <link rel="stylesheet" href="assets/css/feathericon.min.css">
    <link rel="stylehseet" href="https://cdn.oesmith.co.uk/morris-0.5.1.css">
    <link rel="stylesheet" href="assets/plugins/morris/morris.css">
    <link rel="stylesheet" href="assets/css/style.css">

<div class="row">
    <div class="col-lg-12 margin-tb">
        <div class="pull-left">
            <h2>Add New Movie</h2>
        </div>
        <div class="pull-right">
            <a class="btn btn-primary" href="{{ url('/') }}"> Back</a>
        </div>
    </div>
</div>
      
@if ($errors->any())
    <div class="alert alert-danger">
        <strong>Whoops!</strong> There were some problems with your input.<br><br>
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif
 
<form action="{{ route('store') }}" method="POST" enctype="multipart/form-data">
    @csrf
     <div class="row">
        
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Title:</strong>
                <input type="text" name="title" class="form-control" placeholder="Title">
            </div>
        </div> 

        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Movie Url:</strong>
                <input type="text" name="movie_url" class="form-control" placeholder="Movie Url">
            </div>
        </div>

        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Thumbnail:</strong>
                <input type="file" name="thumbnail" class="form-control" placeholder="Thumbnail">
            </div>
        </div>

        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Description:</strong>
                <textarea class="form-control" style="height:150px" name="description" placeholder="Description"></textarea>
            </div>
        </div>

        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Language:</strong>
                <input type="text" name="language" class="form-control" placeholder="Language">
            </div>
        </div>

        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Year:</strong>
                <input type="text" name="year" class="form-control" placeholder="Year">
            </div>
        </div>
    
        <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                <button type="submit" class="btn btn-primary">Submit</button>
        </div>
    </div>
      
</form>

<script data-cfasync="false" src="../../../cdn-cgi/scripts/5c5dd728/cloudflare-static/email-decode.min.js"></script>
    <script src="assets/js/jquery-3.5.1.min.js"></script>
    <script src="assets/js/popper.min.js"></script>
    <script src="assets/js/bootstrap.min.js"></script>
    <script src="assets/plugins/slimscroll/jquery.slimscroll.min.js"></script>
    <script src="assets/plugins/raphael/raphael.min.js"></script>
    <script src="assets/plugins/datatables/jquery.dataTables.min.js"></script>
    <script src="assets/plugins/datatables/datatables.min.js"></script>
    <script src="assets/js/script.js"></script>

@endsection

resources/views/movies/edit.blade.php
@extends('adminLayout')
  
@section('content')
<div class="bg-light m-4 p-4 rounded">
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Edit Movie</h2>
            </div>
           
        </div>
    </div>
      
    @if ($errors->any())
        <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif
     
    <form action="{{ route('updateMovie',$movie->id) }}" method="POST" enctype="multipart/form-data">
    @csrf
    @method('PUT')
    <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
            <strong>Title:</strong>
            <input type="text" name="title" value="{{ $movie->title }}" class="form-control" placeholder="Title">
        </div>
    </div> 
    <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
            <strong>Movie Url:</strong>
            <input type="text" name="movie_url" value="{{ $movie->movie_url }}" class="form-control" placeholder="Movie Url">
        </div>
    </div>

    <!-- Image -->
    <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
            <strong>Thumbnail:</strong>
            <input type="file" name="thumbnail" value="/images/thumbnails/{{ $movie->thumbnail }}" class="form-control" placeholder="Thumbnail">
            <br>
            <img src="/images/thumbnails/{{ $movie->thumbnail }}" width="500px">

        </div>
    </div>
    <br>

    <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
            <strong>Description:</strong>
            <textarea class="form-control" style="height:150px" name="description" placeholder="Description">{{ $movie->description }}</textarea>
        </div>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Year:</strong>
                <input type="text" name="year" value="{{ $movie->year }}" class="form-control" placeholder="Year">
            </div>
        </div>
        <!-- Dates -->
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Created At:</strong>
                {{ $movie->created_at->format('m/d/Y H:i') }}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Updated At:</strong>
                {{ $movie->updated_at->format('m/d/Y H:i') }}
            </div>
        </div>
        <!-- Buttons -->
        <div class="col-xs-12 col-sm-12 col-md-12 text-center">
            <button type="submit" class="btn btn-primary">Submit</button> 
            <a class="btn btn-secondary" href="{{ route('index') }}"> Back</a>
        </div>
    </form>
</div>  



@endsection

resources/views/movies/index.blade.php
@extends('adminLayout')

@section('content')

<!-- from here -->
<div class="page-wrapper">
    <div class="content container-fluid">
        <div class="page-header">
            <div class="row align-items-center">
                <div class="col">
                    <div class="mt-5">
                        <h4 class="card-title float-left mt-2">Movie Controller</h4> <a href="{{ route('movies.create') }}" class="btn btn-primary btn-rounded float-right veiwbutton">Add Movie</a> </div>

                </div>
            </div>
        </div>
<!-- to here -->

        <div class="row">
                <div class="col-12">
                    <div class="card card-table">
                        <div class="card-body booking_card">
                            <div class="table-responsive">
                                <table class="datatable table table-stripped table table-hover table-center mb-0">
                                    
                                    @if ($message = Session::get('success'))
                                        <div class="alert alert-success">
                                            <p>{{ $message }}</p>
                                        </div>
                                    @endif

                                    <thead>
                                        <tr>
                        <!-- Movie ID -->   <!-- <th>MID</th> -->
                        <!-- Thumbnail -->  <th>Thumbnail</th>
                        <!-- Title -->      <th>Title</th>
                        <!-- Movie Url -->  <th>Movie Url</th>
                        <!-- Description --><th>Description</th>
                        <!-- Language -->   <th>Language</th>
                        <!-- Year -->       <th>Year</th>
                        <!-- Created at --> <th>Created at</th>
                        <!-- Updated at --> <th>Updated at</th>
                        <!-- Action -->     <th class="text-right">Status</th>
                        <!-- Actions --> <th>Actions</th>
                                        </tr>
                                    </thead>

                                    @foreach ($movies as $movie)

                                    <tbody>
                                        <tr class="<i style></i>">
                        <!-- Movie ID -->   <!-- <td>{{ ++$i }}</td> -->
                        <!-- Thumbnail -->  <td>
                                                <h2 class="table-avatar">
                                                <a href="#" class="mr-2">
                                                <img class="pill" src="/images/thumbnails/{{ $movie->thumbnail }}" width="80px"><!--width="80px"-->
                                                </h2>
                                            </td>
                        <!-- Title -->      <td>{{ $movie->title }}</td>
                        <!-- Movie Url -->  <td>{{ $movie->movie_url }}</td>
                        <!-- Description --><td style="text-overflow: clip">{{ $movie->description }}</td>
                        <!-- Language -->   <td>{{ $movie->language }}</td>
                        <!-- Year -->       <td>{{ $movie->year }}</td>
                        <!-- Created at --> <td>{{ $movie->created_at->format('m/d/Y H:i') }}</td>
                        <!-- Updated at --> <td>{{ $movie->updated_at->format('m/d/Y H:i') }}</td>
                                            
                        <!-- Status -->     <td>
                                                <div class="actions"> <a href="#" class="btn btn-sm bg-success-light mr-2">Active</a> </div>
                                            </td>
                        <!-- Action -->     <td class="text-right">
                                                <div class="dropdown dropdown-action"> <a href="#" class="action-icon dropdown-toggle" data-toggle="dropdown" aria-expanded="false"><i class="fas fa-ellipsis-v ellipse_color"></i></a>
                                                    <div class="dropdown-menu dropdown-menu-right"> 
                                                        <!-- Edit -->
                                                        <a class="dropdown-item" href="{{ route('show',$movie->id) }}"><i class="fas fa-pencil-alt m-r-5"></i> Edit</a> 
                                                        @csrf
                                                        <!-- Delete -->
                                                        @method('DELETE')
                                                        <a class="dropdown-item" href="{{ route('edit',$movie->id) }}" data-toggle="modal" data-target="#delete_asset"><i class="fas fa-trash-alt m-r-5"></i> Delete</a> </div>
                                                </div>
                                            </td>
                                        </tr>  
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

<!-- here -->

                
    

<!-- to here -->
    @endforeach



{!! $movies->links() !!}
@endsection

resources/views/movies/show.blade.php
@extends('adminLayout')
  
@section('content')
<div class="bg-light m-4 p-4 rounded">
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Movie</h2>
            </div>
        </div>
    </div>
          
    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
              <div class="form-group">
                  <strong>Title:</strong>
                  {{ $movie->title }}
              </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
              <div class="form-group">
                  <strong>Movie Url:</strong>
                  {{ $movie->movie_url }}
              </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
              <div class="form-group">
                  <strong>Thumbnail:</strong><br>
                  <img src="/images/thumbnails/{{ $movie->thumbnail }}" width="500px">
              </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
              <div class="form-group">
                  <strong>Description:</strong>
                  {{ $movie->description }}
              </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
              <div class="form-group">
                  <strong>Year:</strong>
                  {{ $movie->year }}
              </div>
          </div>
          <div class="col-xs-12 col-sm-12 col-md-12">
              <div class="form-group">
                  <strong>Date Created:</strong>
                  {{ $movie->created_at->format('m/d/Y H:i') }}
              </div>
          </div>
          <div class="col-xs-12 col-sm-12 col-md-12">
              <div class="form-group">
                  <strong>Date Updated:</strong>
                  {{ $movie->updated_at->format('m/d/Y H:i') }}
              </div>
          </div>
    </div>
    <div class="mt-4">
        <a class="btn btn-primary" href="{{ route('edit',$movie->id) }}">Edit</a>
        <a class="btn btn-secondary" href="{{ route('index') }}"> Back</a>
    </div> 
</div>

<div class="row">
        <div class="col-12">
            <div class="card">
                <div class="row card-body">
                    <img class="col-sm-4" src="/images/thumbnails/{{ $movie->thumbnail }}" width="100px" alt="sans"/>
                    <div class="col-sm-8">
                        <h5 class="card-title">{{ $movie->title }}</h5>
                        <p class="card-text">{{ $movie->description }}</p>
                       <a href="#" class="btn btn-info">Edit</a>
                   </div>
                </div>     
            </div>
        </div>
    </div>
    </tr>

@endsection